spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/likhithmedisetti007/properties.git
          default-label: master
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: /actuator/health
    
server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: '*'